server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "health","prometheus", "metrics" ]
      base-path: '/actuator'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
